# Generated by Django 2.2 on 2020-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=10, unique=True, verbose_name='卡号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位名称')),
                ('job_name', models.CharField(blank=True, max_length=20, verbose_name='工种名称')),
                ('level', models.CharField(blank=True, max_length=10, verbose_name='级别')),
                ('kind', models.CharField(blank=True, max_length=10, verbose_name='用工种类')),
                ('education', models.CharField(blank=True, default='本科', max_length=10, verbose_name='学历')),
                ('birthday', models.DateField(blank=True, verbose_name='出生日期')),
                ('blood', models.CharField(blank=True, default='A型', max_length=8, verbose_name='血型')),
                ('identity', models.CharField(blank=True, max_length=18, unique=True, verbose_name='身份证号码')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='家庭住址')),
                ('gh', models.CharField(blank=True, max_length=10, verbose_name='工号')),
                ('marriage', models.CharField(blank=True, default='已婚', max_length=8, verbose_name='婚姻状况')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机')),
                ('job_time', models.DateField(blank=True, verbose_name='参加工作时间')),
                ('native', models.CharField(blank=True, max_length=50, verbose_name='籍贯')),
                ('content', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'ordering': ['card'],
            },
        ),
    ]
